import {
    Buildings,
    FileText,
    InfoCircle,
    User,
    Phone,
    Map,
    Global,
    Document,
    Hashtag,
    UserCircle,
    Cpu,
    Card,
    Letter,
    Buildings2,
} from "@solar-icons/react";
import type { FormField, FormGroup } from "../../../components/ux/ModalComponent";
import type { Company, CompanyFormValues } from "../types/company";

export const getCompanyFormFields = (): FormField[] => {
    return [
        {
            name: "name",
            label: "Nombre de la Empresa",
            type: "text",
            placeholder: "Ingresa el nombre de la empresa",
            required: true,
            colSpan: 1,
            startContent: <Buildings size={16} className="text-default-400" />,
            group: "Información Básica",
            validation: {
                required: "El nombre es requerido",
                minLength: {
                    value: 3,
                    message: "El nombre debe tener al menos 3 caracteres",
                },
                maxLength: {
                    value: 100,
                    message: "El nombre no puede exceder los 100 caracteres",
                },
            },
        },
        {
            name: "status",
            label: "Estado",
            type: "select",
            placeholder: "Selecciona el estado",
            required: false,
            colSpan: 1,
            startContent: <InfoCircle size={16} className="text-default-400" />,
            group: "Información Básica",
            options: [
                { value: "ACTIVE", label: "Activo" },
                { value: "INACTIVE", label: "Inactivo" },
                { value: "DELETED", label: "Eliminado" },
            ],
        },
        {
            name: "description",
            label: "Descripción",
            type: "textarea",
            placeholder: "Ingresa una descripción de la empresa",
            required: false,
            colSpan: 2,
            startContent: <FileText size={16} className="text-default-400" />,
            group: "Información Básica",
            rows: 3,
        },
        {
            name: "email",
            label: "Correo Electrónico",
            type: "email",
            placeholder: "contacto@empresa.com",
            required: false,
            colSpan: 1,
            startContent: <Letter size={16} className="text-default-400" />,
            group: "Información de Contacto",
            validation: {
                pattern: {
                    value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                    message: "Ingresa un correo electrónico válido",
                },
            },
        },
        {
            name: "phone",
            label: "Teléfono",
            type: "text",
            placeholder: "+51 987 654 321",
            required: false,
            colSpan: 1,
            startContent: <Phone size={16} className="text-default-400" />,
            group: "Información de Contacto",
        },
        {
            name: "website",
            label: "Sitio Web",
            type: "text",
            placeholder: "https://www.empresa.com",
            required: false,
            colSpan: 2,
            startContent: <Global size={16} className="text-default-400" />,
            group: "Información de Contacto",
        },
        {
            name: "emails",
            label: "Correos Adicionales",
            type: "text",
            placeholder: "correo1@empresa.com, correo2@empresa.com",
            required: false,
            colSpan: 1,
            startContent: <Letter size={16} className="text-default-400" />,
            group: "Información de Contacto",
            description: "Separa los correos con comas",
        },
        {
            name: "phones",
            label: "Teléfonos Adicionales",
            type: "text",
            placeholder: "+51 987 654 321, +51 987 654 322",
            required: false,
            colSpan: 1,
            startContent: <Phone size={16} className="text-default-400" />,
            group: "Información de Contacto",
            description: "Separa los teléfonos con comas",
        },

        {
            name: "address",
            label: "Dirección",
            type: "textarea",
            placeholder: "Ingresa la dirección completa",
            required: false,
            colSpan: 2,
            startContent: <Map size={16} className="text-default-400" />,
            group: "Ubicación",
            rows: 2,
        },

        {
            name: "taxIdentifierType",
            label: "Tipo de Identificador Fiscal",
            type: "select",
            placeholder: "Selecciona el tipo",
            required: false,
            colSpan: 1,
            startContent: <Document size={16} className="text-default-400" />,
            group: "Información Fiscal",
            options: [
                { value: "RUC", label: "RUC (Perú/Ecuador)" },
                { value: "RFC", label: "RFC (México)" },
                { value: "NIT", label: "NIT (Colombia/Centroamérica)" },
                { value: "CUIT", label: "CUIT (Argentina)" },
                { value: "RUT", label: "RUT (Chile/Uruguay)" },
                { value: "CIF", label: "CIF/NIF (España)" },
                { value: "EIN", label: "EIN (Estados Unidos)" },
                { value: "CE", label: "Carnet de Extranjería" }
            ],
        },
        {
            name: "taxIdentifierValue",
            label: "Número de Identificador",
            type: "text",
            placeholder: "20512345678",
            required: false,
            colSpan: 1,
            startContent: <Hashtag size={16} className="text-default-400" />,
            group: "Información Fiscal",
            validation: {
                minLength: {
                    value: 8,
                    message: "El identificador debe tener al menos 8 dígitos",
                },
                maxLength: {
                    value: 15,
                    message: "El identificador no puede exceder los 15 dígitos",
                },
            },
        },

        {
            name: "maxTenantsCreated",
            label: "Máx. Inquilinos",
            type: "number",
            placeholder: "10",
            required: false,
            colSpan: 1,
            startContent: <UserCircle size={16} className="text-default-400" />,
            group: "Capacidades",
            validation: {
                min: {
                    value: 0,
                    message: "El valor debe ser mayor o igual a 0",
                },
            },
        },
        {
            name: "maxDevicesCreated",
            label: "Máx. Dispositivos",
            type: "number",
            placeholder: "100",
            required: false,
            colSpan: 1,
            startContent: <Cpu size={16} className="text-default-400" />,
            group: "Capacidades",
            validation: {
                min: {
                    value: 0,
                    message: "El valor debe ser mayor o igual a 0",
                },
            },
        },
        {
            name: "maxUsersCreated",
            label: "Máx. Usuarios",
            type: "number",
            placeholder: "50",
            required: false,
            colSpan: 1,
            startContent: <User size={16} className="text-default-400" />,
            group: "Capacidades",
            validation: {
                min: {
                    value: 0,
                    message: "El valor debe ser mayor o igual a 0",
                },
            },
        },
        {
            name: "maxDriversCreated",
            label: "Máx. Conductores",
            type: "number",
            placeholder: "20",
            required: false,
            colSpan: 1,
            startContent: <Card size={16} className="text-default-400" />,
            group: "Capacidades",
            validation: {
                min: {
                    value: 0,
                    message: "El valor debe ser mayor o igual a 0",
                },
            },
        },
        {
            name: "tenantAccess",
            label: "Acceso del Inquilino",
            type: "text",
            placeholder: "Ej: tenant-empresa-01",
            required: true,
            colSpan: 2,
            startContent: <Buildings size={16} className="text-default-400" />,
            group: "Capacidades",
            description: "Identificador único para el acceso del inquilino",
            validation: {
                required: "El acceso del inquilino es requerido",
                minLength: {
                    value: 3,
                    message: "El acceso debe tener al menos 3 caracteres",
                },
                maxLength: {
                    value: 50,
                    message: "El acceso no puede exceder los 50 caracteres",
                },
                pattern: {
                    value: /^[a-z0-9-]+$/,
                    message: "Solo se permiten letras minúsculas, números y guiones",
                },
            },
        },
        {
            name: "logo",
            label: "Logo (URL)",
            type: "text",
            placeholder: "https://empresa.com/logo.png",
            required: false,
            colSpan: 1,
            startContent: <Buildings2 size={16} className="text-default-400" />,
            group: "Branding",
        },
        {
            name: "bannerUrl",
            label: "Banner (URL)",
            type: "text",
            placeholder: "https://empresa.com/banner.png",
            required: false,
            colSpan: 1,
            startContent: <Buildings2 size={16} className="text-default-400" />,
            group: "Branding",
        },
    ];
};

export const getCompanyFormGroups = (): FormGroup[] => [
    {
        title: "Información Básica",
        icon: <InfoCircle size={18} weight="Bold" />,
        description: "Datos principales de la empresa",
        fields: ["name", "description", "status"],
    },
    {
        title: "Información de Contacto",
        icon: <User size={18} weight="Bold" />,
        description: "Datos de contacto de la empresa",
        fields: ["email", "phone", "website", "emails", "phones"],
    },
    {
        title: "Ubicación",
        icon: <Map size={18} weight="Bold" />,
        description: "Dirección de la empresa",
        fields: ["address"],
    },
    {
        title: "Información Fiscal",
        icon: <Document size={18} weight="Bold" />,
        description: "Datos fiscales y legales",
        fields: ["taxIdentifierType", "taxIdentifierValue"],
    },
    {
        title: "Capacidades",
        icon: <Cpu size={18} weight="Bold" />,
        description: "Límites y capacidades",
        fields: ["maxTenantsCreated", "maxDevicesCreated", "maxUsersCreated", "maxDriversCreated"],
    },
    {
        title: "Branding",
        icon: <Buildings2 size={18} weight="Bold" />,
        description: "Imagen corporativa",
        fields: ["logo", "bannerUrl"],
    },
];

export const getCompanyInitialValues = (): CompanyFormValues => ({
    name: "",
    description: "",
    address: "",
    phone: "",
    email: "",
    website: "",
    logo: "",
    bannerUrl: "",
    taxIdentifierType: "",
    taxIdentifierValue: "",
    phones: "",
    emails: "",
    status: "ACTIVE",
    maxTenantsCreated: 0,
    maxDevicesCreated: 0,
    maxUsersCreated: 0,
    maxDriversCreated: 0,
    tenantAccess: ""
});

export const mapCompanyToFormValues = (company: Company): CompanyFormValues => ({
    name: company.name || "",
    description: company.description || "",
    address: company.address || "",
    phone: company.phone || "",
    email: company.email || "",
    website: company.website || "",
    logo: company.logo || "",
    bannerUrl: company.bannerUrl || "",
    taxIdentifierType: company.taxIdentifierType || "",
    taxIdentifierValue: company.taxIdentifierValue || "",
    phones: company.phones ? company.phones.join(", ") : "",
    emails: company.emails ? company.emails.join(", ") : "",
    status: company.status || "ACTIVE",
    maxTenantsCreated: company.maxTenantsCreated || 0,
    maxDevicesCreated: company.maxDevicesCreated || 0,
    maxUsersCreated: company.maxUsersCreated || 0,
    maxDriversCreated: company.maxDriversCreated || 0,
    tenantAccess: company.tenantAccess || "",
});