import type { Medidor } from "../types/medidor";

export const MOCK_MEDIDORES: Medidor[] = [
  {
    id: "1",
    numeroSerie: "D23123123",
    codigoPod: "POD-LIMA-2D",
    imei: "741412482350118",
    marca: "METERSIT S.R.L.",
    modelo: "MTSB-033",
    tipoMedidor: "Agua",
    tecnologiaRed: "SIGFOX",
    empresaCliente: "Mibanco - Huaycán",
    empresaProveedora: "Flusytec SAC",
    direccion: "Av. Javier Prado Este 1234, Lima",
    latitud: "12.34",
    longitud: "12.34",
    valorInicial: 0,
    fechaInstalacion: "2026-02-10",
    estado: "pendiente",
  },
  {
    id: "2",
    numeroSerie: "D23124099",
    codigoPod: "POD-LIMA-3A",
    imei: "741412482350221",
    marca: "SENSUS",
    modelo: "SEN-620",
    tipoMedidor: "Agua",
    tecnologiaRed: "NB-IoT",
    empresaCliente: "Mibanco - Canto Grande",
    empresaProveedora: "Flusytec SAC",
    direccion: "Jr. Los Robles 452, San Juan de Lurigancho",
    latitud: "-11.98",
    longitud: "-77.00",
    valorInicial: 120,
    fechaInstalacion: "2026-01-22",
    estado: "activo",
  },
  {
    id: "3",
    numeroSerie: "D23119887",
    codigoPod: "POD-LIMA-1C",
    imei: "741412482350309",
    marca: "ITRON",
    modelo: "ITR-CF51",
    tipoMedidor: "Agua",
    tecnologiaRed: "SIGFOX",
    empresaCliente: "Nestlé - Planta Lima",
    empresaProveedora: "AquaTech Perú",
    direccion: "Av. Argentina 3456, Callao",
    latitud: "-12.02",
    longitud: "-77.11",
    valorInicial: 0,
    fechaInstalacion: "2025-11-05",
    estado: "inactivo",
  },
];